### ISSUE TITLE
Feature: User can view a list of breeds.

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of cat breeds.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can scroll though a list of cat breeds.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-04-13 at 11 22 19 AM](https://user-images.githubusercontent.com/78885956/114601772-c154b880-9c4a-11eb-9ccf-5a39576ce84b.png)

![Screen Shot 2021-04-13 at 11 22 37 AM](https://user-images.githubusercontent.com/78885956/114601830-cfa2d480-9c4a-11eb-9301-59eb95cc73f4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create header
- [x] Add div to html body for container
- [x] add placeholder elements to style
- [x] add styling
- [x] add XMLHttpRequest
- [x] create DOM tree function
- [x] loop through xml response and append to page using DOM tree function
- [x] once data is showing up on page remove placeholder elements
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
