### ISSUE TITLE
Feature: User can view random cat fact

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/ajax-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a random cat fact

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on new fact button to see a new random cat fact

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-04-20 at 5 37 42 PM](https://user-images.githubusercontent.com/78885956/115480356-2dad5a00-a1ff-11eb-82c9-63b9ffaa31d2.png)
![Screen Shot 2021-04-20 at 5 37 57 PM](https://user-images.githubusercontent.com/78885956/115480357-2ede8700-a1ff-11eb-8ae0-6ff9288c0048.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add container for random fact view
- [x] add title
- [x] add placeholder fact in div
- [x] add new fact button
- [x] add styling
- [x] add random fact link to header
- [x] in header event listener if target is cat fact make cat fact view visible, hide others.
- [x] add event listener to new fact button
- [x] in callback function create new XMLHttpRequest
- [x] in request callback function change text content of fact div to xml response fact
- [x] change data.view for fact view
- [x] add fact view condition to contentLoadHandler
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
