### ISSUE TITLE
Feature: User can view information for a selected breed

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view information on a selected breed.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on name or image to view information on that breed

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-04-13 at 5 36 11 PM](https://user-images.githubusercontent.com/78885956/114637719-db0ff300-9c7e-11eb-99ef-cf28912c19bd.png)
![Screen Shot 2021-04-13 at 5 36 23 PM](https://user-images.githubusercontent.com/78885956/114637727-dd724d00-9c7e-11eb-942b-9f00f99e2d5a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add placeholder for cat info view
- [x] add styling for cat info view
- [x] add Dom tree function for cat info (data-view: cat name)
- [x] loop through xml response and append cat info to page
- [x] remove placeholders
- [x] add event listener to breeds view container
- [x] if event target class name is cat-name or cat-img
- [x] loop through all info views
- [x] if list data-view is same as event target data-view
- [x]  class name not hidden (hide breed list view also)
- [x] else class name hidden
- [x] add event listener on header
- [x] in callback if event target is breed button: hide info view, unhide list view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
