### ISSUE TITLE
Feature: User can save a breed to their favorites

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a breed to their favorites
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
user can click star next to cat info and save that cat to their favorites.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-04-15 at 10 10 46 AM](https://user-images.githubusercontent.com/78885956/114910616-f7bd3f80-9dd2-11eb-9b06-6243e2aea52b.png)
![Screen Shot 2021-04-15 at 10 11 15 AM](https://user-images.githubusercontent.com/78885956/114910637-fdb32080-9dd2-11eb-8f29-08478ef35d1a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add placeholder elements
- [x] add styling
- [x] add data model
- [x] add local storage to save data model before unload
- [x] add Dom tree function for adding favorites
- [x] add event listener to info-views
- [x] use getinfo callback function
- [x] add if event target is star: add cat to favorites in data model, append cat to favorites view, change star to filled in
- [x] add domcontentloaded event
- [x] in header event listener if target is favorites: show favorites view, hide other views
- [x] add view to data model
- [x] on domcontent loaded keep view same
- [x] on info view if breed is in favorites, have star be filled in.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
